name: 'Build Notify Bot'

on:
  push:
    branches: [master]

jobs:
  build:
    env:
      RUSTFLAGS: "-D warnings"
    name: Bot Build
    runs-on: ubuntu-latest

    steps:
      # Download Source Code
      - name: Git Checkout
        uses: actions/checkout@v3

      # Install Dependencies
      - name: Install Dependencies
        run: 'sudo apt-get update && sudo apt-get install -y --no-install-recommends openssl sqlite build-essential libmariadb-dev-compat libpq-dev libssl-dev pkgconf'

      # Cache
      - name: Add sccache
        uses: Swatinem/rust-cache@v1

      # Install toolchain
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          component: rustfmt, clippy

      # Run cargo clippy, abort with warnings
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --release -- -D warnings

      # Check code format
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      # Build it
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      # Uplaod the binary
      - uses: actions/upload-artifact@v3
        with:
          name: notify-bot
          path: target/release/notify-bot
